-- ============================================
-- 五险一金计算器 - Supabase 数据库设置
-- ============================================

-- 1. 创建 cities 表 (城市标准表)
CREATE TABLE IF NOT EXISTS cities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city_name TEXT NOT NULL,
  year TEXT NOT NULL,
  rate FLOAT NOT NULL,
  base_min INTEGER NOT NULL,
  base_max INTEGER NOT NULL
);

-- 2. 创建 salaries 表 (员工工资表)
CREATE TABLE IF NOT EXISTS salaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id TEXT NOT NULL,
  employee_name TEXT NOT NULL,
  month TEXT NOT NULL,
  salary_amount INTEGER NOT NULL
);

-- 3. 创建 results 表 (计算结果表)
CREATE TABLE IF NOT EXISTS results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_name TEXT NOT NULL,
  avg_salary FLOAT NOT NULL,
  contribution_base FLOAT NOT NULL,
  company_fee FLOAT NOT NULL
);

-- 4. 为开发暂时禁用 RLS (Row Level Security)
-- 注意: 生产环境中应该正确配置 RLS 策略
ALTER TABLE cities ENABLE ROW LEVEL SECURITY;
ALTER TABLE salaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE results ENABLE ROW LEVEL SECURITY;

-- 允许所有操作 (仅用于开发)
CREATE POLICY "Allow all access on cities" ON cities FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access on salaries" ON salaries FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access on results" ON results FOR ALL USING (true) WITH CHECK (true);

-- 5. 创建一些辅助索引
CREATE INDEX IF NOT EXISTS idx_salaries_employee_name ON salaries(employee_name);
CREATE INDEX IF NOT EXISTS idx_salaries_month ON salaries(month);
CREATE INDEX IF NOT EXISTS idx_cities_city_name ON cities(city_name);
